version: "3.8"
services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/contacts-db
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma generate && npm run start:dev"

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3000"  # 👈 fixed
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  db_data:
